# Generated by Django 2.1.1 on 2018-10-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=120)),
            ],
        ),
    ]
